FileVersion = 1
Dependencies = {corlib = "*", MiniZ = "*", Bulkan = "*", "Bulkan.Utilities" = "*", StbImageBeef = "*"}

[Project]
Name = "nova"
StartupObject = "Nova.Program"
DefaultNamespace = "Nova"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/libs/OpenImageDenoise.lib", "$(ProjectDir)/libs/bvh_builder.lib", "$(ProjectDir)/libs/lua54.lib", "$(ProjectDir)/libs/cgltf.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/libs/*.dll\", \"$(TargetDir)\")"]
VectorizeLoops = true
VectorizeSLP = true

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/libs/OpenImageDenoise.lib", "$(ProjectDir)/libs/bvh_builder.lib", "$(ProjectDir)/libs/lua54.lib", "$(ProjectDir)/libs/cgltf.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/libs/*.dll\", \"$(TargetDir)\")"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)/libs/OpenImageDenoise.lib", "$(ProjectDir)/libs/bvh_builder.lib", "$(ProjectDir)/libs/lua54.lib", "$(ProjectDir)/libs/cgltf.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/libs/*.dll\", \"$(TargetDir)\")"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/libs/OpenImageDenoise.lib", "$(ProjectDir)/libs/bvh_builder.lib", "$(ProjectDir)/libs/lua54.lib", "$(ProjectDir)/libs/cgltf.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/libs/*.dll\", \"$(TargetDir)\")"]
