[package]
name = "terra"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.2"
smallvec = "1.15.1"
glam = { version = "0.30.10", features = ["bytemuck"] }
png = "0.18.0"
bytemuck = "1.24.0"
kdam = "0.6.4"
bevy_mikktspace = "0.16.1"
zune-hdr = "0.4.0"
clap = { version = "4.5.54", features = ["derive"] }
bytesize = "2.3.1"
profiling = "=1.0.17"
hecs = "0.11.0"
ufbx = "0.10.1"

[dependencies.gltf]
git = "https://github.com/gltf-rs/gltf.git"
rev = "3def30c9caf96f2dbc85238179ea5a6152c5cf22"
features = ["KHR_texture_transform", "KHR_lights_punctual", "KHR_materials_emissive_strength", "KHR_materials_ior", "KHR_materials_specular", "KHR_materials_clearcoat"]

[dependencies.image]
version = "0.25.9"
default-features = false
features = ["rayon", "png", "jpeg"]

[dependencies.tracy-client]
version = "=0.18.4"
features = ["flush-on-exit"]
optional = true

[features]
tracy = ["dep:tracy-client", "profiling/profile-with-tracy"]
